apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pingserverresources.chorgi.io
spec:
  group: chorgi.io
  names:
    kind: PingServerResource
    plural: pingserverresources
    singular: pingserverresource
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              replicas:
                type: integer
            type: object
          status:
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
